### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by bryanbridges** [shinh/maloader#23]
sudo make release
make clean
make[1]: Entering directory '/root/Downloads/maloader'
rm -f *.o *.d */*.o */*.d libmac.so extract macho2elf ld-mac
make[1]: Leaving directory '/root/Downloads/maloader'
make all "GCC_EXTRA_FLAGS=-DNOLOG -DNDEBUG"
make[1]: Entering directory '/root/Downloads/maloader'
cc -g -Iinclude -Wall -MMD -fno-omit-frame-pointer -O -DNOLOG -DNDEBUG -fPIC   -c -o libmac/mac.o libmac/mac.c
cc -shared libmac/mac.o libmac/strmode.c -g -Iinclude -Wall -MMD -fno-omit-frame-pointer -O -DNOLOG -DNDEBUG -fPIC -o libmac.so -DNOLOG -DNDEBUG  -luuid -lz
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
Makefile:92: recipe for target 'libmac.so' failed
make[1]: *** [libmac.so] Error 1
make[1]: Leaving directory '/root/Downloads/maloader'
Makefile:47: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by shinh** [comment]
Please install libz

**Comment by jknair0** [comment]
Can you tell me how to install libz?

**Comment by shinh** [comment]
It depends on which OS you are using. The most generic answer is: https://zlib.net/ Perhaps googling with "zlib <name of your OS> install" would help.
